### ISSUE TITLE
Error when trying to send email on dev environment

### ISSUE THREAD

**Issue by RafaelR7** [dylanshine/sendgrid_mailer#1]
Hi, first thank you for creating this package, 
I was successfully sending emails when I was testing on my develop environment, but when I tested on my prod environment I started to get error, the only difference from the environments are different firestore databases.
Do you know what might be the problem?

**Comment by RafaelR7** [comment]
sorry, I found out that I need to use another sendgrid api key

**Comment by dylanshine** [comment]
No worries!

If you wouldn't mind giving the package a like on pub.dev, I'd
really appreciate it.

Best,
Dylan Shine

<https://www.shinelabs.dev>
dylan@shinelabs.dev | 716.289.7406
