### ISSUE TITLE
XMLHttpRequest error in Flutter Web

### ISSUE THREAD

**Issue by sachavieuxroy** [dylanshine/sendgrid_mailer#14]
This pluggin has worked & is still working on my SAMSUNG Note 8 with Android 8 in Flutter Android, but gives  " (ClientException) XMLHttpRequest error " in Flutter web.

[link to json payload](https://www.dropbox.com/s/3aspnm4f1086e10/json%20payload.txt?dl=0) 

[link to dart file that uses dart plugin](https://www.dropbox.com/s/ftf1no8wxz5718j/contact_screen.dart?dl=0) 

[link to download github project](https://www.dropbox.com/s/7exsparjam845go/sachavieuxroycom-master.zip?dl=0) 

![await mailer send](https://user-images.githubusercontent.com/964545/131254902-36c7d491-a0c4-415d-af9d-711e2bba89a9.png)

**Comment by eifachtimon** [comment]
same issue

**Comment by dylanshine** [comment]
Please refer to this issue: https://github.com/dylanshine/sendgrid_mailer/issues/7
