### ISSUE TITLE
XMLHttpRequest error on Flutter Web

### ISSUE THREAD

**Issue by taimoorbh** [dylanshine/sendgrid_mailer#15]
Getting XMLHttpRequest error when sending email from flutter web on iMac.

I even tried adding headers but didnt work out
headers: {
            "Accept": "application/json",
            "Access-Control-Allow-Origin": "*"
     }

**Comment by dylanshine** [comment]
Please refer to this issue: https://github.com/dylanshine/sendgrid_mailer/issues/7
