### ISSUE TITLE
In lib/src/models/email.dart, typo in toJson() breaks custom args.

### ISSUE THREAD

**Issue by ailabs-software** [dylanshine/sendgrid_mailer#16]
See correction below. This should be a simple fix if someone wants to do a pull request.

  Map<String, dynamic> toJson() => <String, dynamic>{
        'personalizations': personalizations.map((e) => e.toJson()).toList(),
        'from': from.toJson(),
        'reply_to': replyTo?.toJson(),
        'subject': subject,
        'content': content?.map((e) => e.toJson()).toList(),
        'attachments': attachments?.map((e) => e.toJson()).toList(),
        'template_id': templateId,
        'headers': headers,
        'categories': categories,
        **'custom_args': customArgs,**
        'send_at': sendAt?.toUtc().millisecondsSinceEpoch,
        'batch_id': batchId,
        'asm': asm?.toJson(),
        'ip_pool_name': ipPoolName,
        'mail_settings': mailSettings?.toJson(),
        'tracking_settings': trackingSettings?.toJson(),
      };

**Comment by dylanshine** [comment]
@bpilot feel free to open a PR if I don't get to it today
