### ISSUE TITLE
changes on version 0.1.2

### ISSUE THREAD

**Issue by RafaelR7** [dylanshine/sendgrid_mailer#3]
Hi, there's a change on the version 0.1.2? Now the Email class has named parameters?
<img width="351" alt="Screen Shot 2020-10-08 at 09 16 48" src="https://user-images.githubusercontent.com/20539985/95457469-55b22b80-0947-11eb-8124-c310c0ec1f1a.png">
 
I was using just like the example on the readme but suddenly it start to throw an error about the Email class expecting 3 parameters but it was getting 4.

Can you please update the readme? Thanks

**Comment by dylanshine** [comment]
Hey @RafaelR7, yes the new version marks content as an optional parameter.
The issue is that I believe I need to push a new version of the library in order for the README changes to appear on pub.dev
